# Generated by Django 3.0.3 on 2020-04-04 05:42

import dianoga_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('trash', 'Trash'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('metal', 'Metal'), ('cardboard', 'Cardboard'), ('glass', 'Glass')], default='Trash', max_length=10)),
                ('file', models.FileField(upload_to=dianoga_app.models.get_upload_to)),
            ],
        ),
    ]
