# Generated by Django 3.0.3 on 2020-04-07 07:56

import dianoga_app.models
import dianoga_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianoga_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('trash', 'Trash'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('metal', 'Metal'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('debug', 'Debug')], default='Debug', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=dianoga_app.models.get_upload_to, validators=[dianoga_app.validators.validate_file_extension]),
        ),
    ]
